### ISSUE TITLE
Remove white padding inside the circle

### ISSUE THREAD

**Issue by ece321** [iamMehedi/PasscodeView#1]
How do I remove the white padding inside the circle?

**Comment by iamMehedi** [comment]
There is no readily available way but that can be pretty easily achieved. You just need to make the `mDigitInnerRadius` equal to the `mDigitRadius` in the `PasscodeView` constructor.

**Comment by ece321** [comment]
Alright, but is there a way to resize the digitInnerRadius?
`passcodeView:digitInnerRadius = "16dp"
 passcodeView:digitRadius = "16dp"`

 I tried doing this in XML, it says "No resource identifier found"

**Comment by iamMehedi** [comment]
No xml attribute is defined for the inner radius. You can add that if you need, just add an attribute in the `attrs.xml` file and then take care of that in the code when provided.

**Comment by ece321** [comment]
Do you mean that I should create another attrs.xml in my project? This is what I did,
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="PasscodeView">
        <attr name="digitInnerRadius" format="dimension" />
        <attr name="digitRadius" format="dimension" />
    </declare-styleable>
</resources>`

And on my XML
`<com.mhk.android.passcodeview.PasscodeView
        android:id="@+id/passcode_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        passcodeView:numDigits="4"
        passcodeView:controlColor="@color/blue"
        passcodeView:controlColorActivated="@color/blue"
        passcodeView:digitColorFilled ="@color/blue"
        passcodeView:digitColorBorder="@color/blue"
        passcodeView:digitRadius = "16dp"
        passcodeView:digitInnerRadius = "16dp"
        android:layout_marginTop="@dimen/activity_vertical_margin" />`

Though I did not encounter the same error anymore, but it did not work.

**Comment by iamMehedi** [comment]
You need to make changes to this library, that's where the `PasscodeView` and it's attributes are. So you'll need to add the extra attribute to the `attrs.xml` file that's already there in the library project and then take care of that attribute's value inside `PasscodeView` class. Just read 1 or 2 tutorials or SO threads on custom view widgets and how to pass custom xml attributes to them and you'll see it's pretty easy.

**Comment by iamMehedi** [comment]
This feature has been added to the lib in version `1.0.3`.
